### ISSUE TITLE
How can we read binary data?

### ISSUE THREAD

**Issue by Dillybob92** [larkjs/lark-websocket#1]
Thanks for this module, I'm loving how lightweight it is :)

Look at my screenshot:
http://i.gyazo.com/faa25a8ff428203f04a16f6e52198219.png

Basically, I am sending some binary data, but the binary Message is not showing up under my socket.on('message' function.

Any idea?

**Comment by Dillybob92** [comment]
Haha I found it I think:
http://i.gyazo.com/5ae18d168c40ec72b0f179e0aa70438f.png

**Comment by viRingbells** [comment]
Seems you have already found it.
use client.on('receive', function (data, client){...}) to handle the binary data.

**Comment by Dillybob92** [comment]
Thank you @viRingbells
